#!/usr/bin/env python
# coding: utf-8

# In[3]:


import pandas as pd 
import numpy as np 
import plotly.express as px 
import plotly.graph_objects as go 
data = pd.read_csv("Screentime-App-Details.csv") 
print(data)


# In[4]:


data.isnull().sum()


# In[5]:


print(data.describe())


# In[6]:


figure = px.bar(data_frame=data ,x = "Date",y = "Usage",color="App",title="Usage") 
figure.show()


# In[7]:


figure = px.bar(data_frame=data ,x = "Date",y = "Notifications",color="App",title="Notifications") 
figure.show()


# In[8]:


figure = px.bar(data_frame=data ,x = "Date",y = "Times opened",color="App", title="Times Opened") 
figure.show()


# In[10]:


figure = px.scatter(data_frame = data ,x="Notifications",y="Usage",size="Notifications",trendline="ols",title = "Relationship Between Number of Notifications and Usage")
figure.show()


# In[ ]:




